# Generated by Django 2.2.5 on 2020-02-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SateliteTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.TextField()),
                ('contador_mensagens', models.PositiveIntegerField()),
                ('nro_pacote1', models.IntegerField()),
                ('nro_pacote2', models.IntegerField()),
                ('nro_pacote3', models.IntegerField()),
                ('latitude_gps', models.FloatField()),
                ('longitude_gps', models.FloatField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('segundo', models.IntegerField()),
                ('hdop', models.IntegerField()),
                ('nro_satelite', models.IntegerField()),
                ('speed', models.FloatField()),
                ('curso', models.FloatField()),
                ('altitude_gps', models.FloatField()),
                ('pot_rec_bal', models.FloatField()),
                ('temp_inter_um', models.FloatField()),
                ('temp_ext', models.FloatField()),
                ('temp_inter_dois', models.FloatField()),
                ('pressao', models.FloatField()),
                ('pressao_mar', models.FloatField()),
                ('altitude_BMP', models.IntegerField()),
                ('pot_tx_no_balao', models.FloatField()),
                ('status_header', models.IntegerField()),
                ('status_temperatura', models.IntegerField()),
                ('ds18b20', models.IntegerField()),
                ('bmp180', models.IntegerField()),
                ('sdcard', models.IntegerField()),
                ('gpsPresent', models.IntegerField()),
                ('potenc_est', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
