# Generated by Django 2.2.5 on 2020-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelitetelemetry',
            name='sync',
            field=models.CharField(max_length=5),
        ),
    ]
