# Generated by Django 3.0.3 on 2020-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200213_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SateliteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalog', models.CharField(max_length=200)),
            ],
        ),
    ]
