# Generated by Django 3.0.3 on 2020-03-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_satelitelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntenaPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_antena', models.FloatField()),
                ('longitude_antena', models.FloatField()),
            ],
        ),
    ]
