# Generated by Django 3.0.3 on 2020-03-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_antenapositions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
