# Generated by Django 3.0.3 on 2020-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200302_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenapositions',
            name='altitude_ant',
            field=models.FloatField(null=True),
        ),
    ]
