# Generated by Django 3.0.3 on 2020-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_antenapositions_altitude_ant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntenaMoviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('azimute', models.FloatField()),
                ('elevação', models.FloatField()),
            ],
        ),
    ]
