# Generated by Django 3.0.3 on 2020-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_antenamoviment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SateliteMensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalog', models.CharField(max_length=60)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(null=True)),
            ],
        ),
    ]
