# Generated by Django 3.0.3 on 2020-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_satelitemensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelitemensagem',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
    ]
