# Generated by Django 3.0.3 on 2020-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200303_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelitemensagem',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
